[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
    Access-Control-Allow-Origin = "*"
    X-Robots-Tag = "all"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    X-Robots-Tag = "all"

[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./public/"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[plugins]]
  package = "netlify-plugin-copy-files"
  [plugins.inputs]
    source = "public"
    destination = ".next"

[[edge_functions]]
  function = "next-server"
  path = "/*"

# Remove the redirect since we're serving directly from public
# The sitemap.xml will be served directly from the public directory 