[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
    Access-Control-Allow-Origin = "*"
    X-Robots-Tag = "all"
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    Surrogate-Control = "no-store"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    X-Robots-Tag = "all"
    Cache-Control = "public, max-age=3600"

[build]
  command = "npm run build && cp -r public/* .next/"
  publish = ".next"

# Ensure static files from public directory are copied to the publish directory
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Copy files from public to .next during build
[[plugins]]
  package = "netlify-plugin-copy-files"
  [plugins.inputs]
    source = "public"
    destination = ".next"

[build.processing]
  skip_processing = false

# Remove redirects as we're serving directly from public directory 