[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
    Access-Control-Allow-Origin = "*"
    X-Robots-Tag = "all"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    X-Robots-Tag = "all"

[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/sitemap.xml"
  to = "/.next/static/sitemap.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/.next/static/robots.txt"
  status = 200

# Remove the redirect since we're serving directly from public
# The sitemap.xml will be served directly from the public directory 